name: Build frontend
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build frontend
        run: |
          cd src/backend
          npm ci
          npm run build --if-present
          zip -r --junk-paths backend dist/main.bundle.js package.json package-lock.json
      - name: Build frontend
        run: |
          cd src/frontend
          npm ci
          npm run build --if-present
          zip -r --junk-paths frontend dist
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./src/frontend/backend.zip
            ./src/frontend/frontend.zip
