name: Build frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
#      - name: Build backend
#        run: |
#          cd src/backend
#          npm ci
#          npm run build --if-present
#          zip --junk-paths harden-backend dist/*
      - name: Build frontend
        run: |
          cd src/frontend
          npm ci
          npm run build --if-present
          zip --junk-paths harden-frontend dist/*
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: harden
          draft: false
          prerelease: false
      - name: Upload release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/frontend/harden-frontend.zip
          asset_name: harden-frontend.zip
          asset_content_type: application/zip
