name: Clean up

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Clean up resources'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az container delete \
              --name HardenWeb \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --yes
            az acr delete \
              --name HardenContainerRegistry \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --yes
