name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    env:
      NODE_ENV: development
      NODE_HOSTNAME: harden.southeastasia.azurecontainer.io
      PORT: 80
      DB_HOST: harden-db.postgres.database.azure.com
      DB_PORT: 5432
      DB_USER: postgres@harden-db
      DB_DATABASE: postgres
      IMAGE_NAME: harden
      IMAGE_TAG: latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG
